include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: false

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes
    avoid_classes_with_only_static_members: false

    avoid_redundant_argument_values: false

    # Unnecessary use of this in constructors should not be done
    unnecessary_this: false

    # source files name using lowercase_with_underscores
    lowercase_with_underscores: false

    include_file_not_found: false

    leading_newlines_in_multiline_strings: false

    always_declare_return_types: false

    type_annotate_public_apis: false
    #always_use_package_imports to make a quick navigation to particular files
    always_use_package_imports: false

    directives_ordering: false

    # In case of production should be set to true
    avoid_print: false

    avoid_unnecessary_containers: false

    prefer_if_elements_to_conditional_expressions: false

    avoid_function_literals_in_foreach_calls: false

    join_return_with_assignment: false

    prefer_const_literals_to_create_immutables: false

    non_constant_identifier_names: false

    constant_identifier_names: false

    prefer_const_constructors: true

    unused_import: false

    use_key_in_widget_constructors: false

    must_be_immutable: false

    deprecated_member_use: false

    unnecessary_getters_setters: false

    missing_return: false

    override_on_non_overriding_member: false

    must_call_super: false